/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RenameApp;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {



    @Override
    public void start(Stage primaryStage) throws Exception {

        Parent root = FXMLLoader.load(getClass().getResource("/view/structure.fxml"));
        Scene scene = new Scene(root, 450, 900);

        primaryStage.setTitle("Rename image files");
        primaryStage.setScene(scene);

        scene.getStylesheets().add(getClass().getResource("/css/style.css").toExternalForm());
        primaryStage.show();

    }

    public static void main(String[] args) { Application.launch();}


}
